In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\mabin\Desktop\DataScienceClassNotes\MLOps_Project_1\ml_ops_project_-_1\data\processed\cleaned_car_v2.csv')
df.head()

                     name   company  year     Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000.0       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000.0          40    Diesel
2      Maruti Suzuki Alto    Maruti  2018  259300.0       22000    Petrol
3       Hyundai Grand i10   Hyundai  2014  325000.0       28000    Petrol
4  Ford EcoSport Titanium      Ford  2014  575000.0       36000    Diesel

In [3]:
df.isnull().sum()

name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     0
dtype: int64

In [5]:
df[df['year'] == df['year'].max()]

,name,company,year,Price,kms_driven,fuel_type
64,Volkswagen Vento Highline,Volkswagen,2019,1200000.00,3600,Diesel
178,Mahindra Jeep MM,Mahindra,2019,390000.00,60,Diesel
182,Mahindra Jeep CL550,Mahindra,2019,379000.00,0,Diesel
235,Maruti Suzuki Swift,Maruti,2019,610000.00,73,Petrol
335,Nissan X Trail,Nissan,2019,1200000.00,300,Diesel
384,Tata Tigor Revotron,Tata,2019,650000.00,100,Diesel
405,Renault Kwid RXT,Renault,2019,370000.00,1000,Petrol
441,Hyundai Verna 1.6,Hyundai,2019,900000.00,2000,Petrol
464,Maruti Suzuki Alto,Maruti,2019,265000.00,9800,Petrol
587,Ford Figo Petrol,Ford,2019,525000.00,0,Petrol
619,Hyundai Creta 1.6,Hyundai,2019,1200000.00,0,Petrol
642,Tata Tiago Revotorq,Tata,2019,568500.00,0,Petrol
643,Tata Nexon,Tata,2019,550635.00,0,Petrol
683,Hyundai Venue,Hyundai,2019,739899.78,7000,Diesel
697,Mahindra KUV100 K8,Mahindra,2019,560000.00,2875,Petrol
699,Ford Endeavor 4x4,Ford,2019,2900000.00,9000,Diesel
704,Maruti Suzuki Alto,Maruti,2019,400000.00,1500,Petrol
707,Maruti Suzuki Alto,Maruti,2019,425000.00,1625,Petrol
708,Maruti Suzuki Alto,Maruti,2019,399750.00,1500,Petrol
719,Toyota Innova 2.0,Toyota,2019,663979.91,4000,Petrol

In [10]:
df[df['name'].str.startswith('BMW')]

                 name company  year      Price  kms_driven fuel_type
71       BMW 3 Series     Bmw  2011   600000.0       60500    Petrol
77       BMW 7 Series     Bmw  2009  1600000.0       35000    Petrol
350      BMW 5 Series     Bmw  2011  1299000.0       49000    Diesel
451  BMW X1 xDrive20d     Bmw  2011  1150000.0       72000    Diesel
471      BMW 5 Series     Bmw  2009   650000.0       37518    Petrol
554      BMW 3 Series     Bmw  2011  1075000.0       35000    Diesel
556  BMW X1 sDrive20d     Bmw  2012  1025000.0       41000    Diesel
581            BMW X1     Bmw  2011  1000000.0       34000    Diesel