In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/processed/cleaned_car_v2.csv')
df.head()

,name,company,year,Price,kms_driven,fuel_type,car_age,is_luxury,kms_per_year
0,Hyundai Santro Xing,Hyundai,2007,11.289794,45000,Petrol,13,0,3214.285714
1,Mahindra Jeep CL550,Mahindra,2006,12.959847,40,Diesel,14,0,2.666667
2,Maruti Suzuki Alto,Maruti,2018,12.412746,22000,Petrol,2,0,7333.333333
3,Hyundai Grand i10,Hyundai,2014,12.691584,28000,Petrol,6,0,4000.000000
4,Ford EcoSport Titanium,Ford,2014,13.262127,36000,Diesel,6,0,5142.857143

In [4]:
df.isnull().sum()

name            0
company         0
year            0
Price           0
kms_driven      0
fuel_type       0
car_age         0
is_luxury       0
kms_per_year    0
dtype: int64

In [5]:
df[df['year'] == df['year'].max()]

,name,company,year,Price,kms_driven,fuel_type,car_age,is_luxury,kms_per_year
64,Volkswagen Vento Highline,Volkswagen,2019,13.997833,3600,Diesel,1,0,1800.0
178,Mahindra Jeep MM,Mahindra,2019,12.873905,60,Diesel,1,0,30.0
182,Mahindra Jeep CL550,Mahindra,2019,12.845294,0,Diesel,1,0,0.0
235,Maruti Suzuki Swift,Maruti,2019,13.321216,73,Petrol,1,0,36.5
335,Nissan X Trail,Nissan,2019,13.997833,300,Diesel,1,0,150.0
384,Tata Tigor Revotron,Tata,2019,13.384729,100,Diesel,1,0,50.0
405,Renault Kwid RXT,Renault,2019,12.821261,1000,Petrol,1,0,500.0
441,Hyundai Verna 1.6,Hyundai,2019,13.710151,2000,Petrol,1,0,1000.0
464,Maruti Suzuki Alto,Maruti,2019,12.487489,9800,Petrol,1,0,4900.0
587,Ford Figo Petrol,Ford,2019,13.171155,0,Petrol,1,0,0.0
619,Hyundai Creta 1.6,Hyundai,2019,13.997833,0,Petrol,1,0,0.0
642,Tata Tiago Revotorq,Tata,2019,13.250758,0,Petrol,1,0,0.0
643,Tata Nexon,Tata,2019,13.019107,0,Petrol,1,0,0.0
683,Hyundai Venue,Hyundai,2019,13.652226,7000,Diesel,1,0,3500.0
697,Mahindra KUV100 K8,Mahindra,2019,13.235694,2875,Petrol,1,0,1437.5
699,Ford Endeavor 4x4,Ford,2019,14.880222,9000,Diesel,1,0,4500.0
704,Maruti Suzuki Alto,Maruti,2019,12.899222,1500,Petrol,1,0,750.0
707,Maruti Suzuki Alto,Maruti,2019,12.959847,1625,Petrol,1,0,812.5
708,Maruti Suzuki Alto,Maruti,2019,12.893457,1500,Petrol,1,0,750.0
719,Toyota Innova 2.0,Toyota,2019,13.208621,4000,Petrol,1,0,2000.0

In [6]:
df[df['name'].str.startswith('BMW')]

,name,company,year,Price,kms_driven,fuel_type,car_age,is_luxury,kms_per_year
71,BMW 3 Series,Bmw,2011,13.304687,60500,Petrol,9,1,6050.000000
77,BMW 7 Series,Bmw,2009,14.285515,35000,Petrol,11,1,2916.666667
350,BMW 5 Series,Bmw,2011,14.077106,49000,Diesel,9,1,4900.000000
451,BMW X1 xDrive20d,Bmw,2011,13.955273,72000,Diesel,9,1,7200.000000
471,BMW 5 Series,Bmw,2009,13.384729,37518,Petrol,11,1,3126.500000
554,BMW 3 Series,Bmw,2011,13.887832,35000,Diesel,9,1,3500.000000
556,BMW X1 sDrive20d,Bmw,2012,13.840204,41000,Diesel,8,1,4555.555556
581,BMW X1,Bmw,2011,13.815512,34000,Diesel,9,1,3400.000000

In [7]:
train_df = pd.read_csv('../data/processed/train.csv')
test_df = pd.read_csv('../data/processed/test.csv')

In [8]:
train_df['company'].unique()

array(['Skoda', 'Maruti', 'Mahindra', 'Tata', 'Toyota', 'Honda',
       'Hyundai', 'Ford', 'Mercedes', 'Datsun', 'Bmw', 'Jaguar',
       'Chevrolet', 'Renault', 'Volkswagen', 'Mitsubishi', 'Audi',
       'Nissan', 'Hindustan', 'Force', 'Fiat', 'Land', 'Volvo', 'Jeep',
       'Mini'], dtype=object)

In [9]:
test_df['company'].unique()

array(['Hyundai', 'Honda', 'Maruti', 'Ford', 'Tata', 'Nissan', 'Mahindra',
       'Bmw', 'Skoda', 'Renault', 'Volkswagen', 'Mercedes', 'Chevrolet',
       'Mitsubishi', 'Toyota', 'Mini', 'Fiat', 'Datsun'], dtype=object)

In [10]:
original_df = pd.read_csv('../data/processed/Cleaned_car_dataset.csv')

In [11]:
missing_col = original_df.isnull().sum()
missing_col

name           0
company        0
year           0
Price         21
kms_driven     0
fuel_type      0
dtype: int64

In [12]:
original_df.loc[original_df['Price'].isna(), 'Price']

2     NaN
5     NaN
114   NaN
231   NaN
237   NaN
302   NaN
354   NaN
400   NaN
408   NaN
421   NaN
463   NaN
506   NaN
510   NaN
523   NaN
643   NaN
683   NaN
687   NaN
708   NaN
714   NaN
719   NaN
740   NaN
Name: Price, dtype: float64

In [14]:
import pathlib
curr_dir = pathlib.Path.cwd()
home_dir = curr_dir.parent.parent.parent
print(home_dir)

c:\Users\mabin\Desktop\DataScienceClassNotes